// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOeuESrmysI7PkHX8ZgTVQu_oBVbxViK8',
    appId: '1:531211508564:web:72e2387193b1515214c6c1',
    messagingSenderId: '531211508564',
    projectId: 'formidable-feat-402810',
    authDomain: 'formidable-feat-402810.firebaseapp.com',
    storageBucket: 'formidable-feat-402810.appspot.com',
    measurementId: 'G-20JBBCCZ7X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG-pyh0KN1Ka5d2CfXOBZwDTf_rBlN2YM',
    appId: '1:531211508564:android:53837c7c4413741b14c6c1',
    messagingSenderId: '531211508564',
    projectId: 'formidable-feat-402810',
    storageBucket: 'formidable-feat-402810.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_3JUDWJbfoF0ygJHAPbCdHAFNc8pI3PY',
    appId: '1:531211508564:ios:dc63920c20bcc19714c6c1',
    messagingSenderId: '531211508564',
    projectId: 'formidable-feat-402810',
    storageBucket: 'formidable-feat-402810.appspot.com',
    iosBundleId: 'com.example.tourInnApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_3JUDWJbfoF0ygJHAPbCdHAFNc8pI3PY',
    appId: '1:531211508564:ios:0be44f3967d0fad314c6c1',
    messagingSenderId: '531211508564',
    projectId: 'formidable-feat-402810',
    storageBucket: 'formidable-feat-402810.appspot.com',
    iosBundleId: 'com.example.tourInnApp.RunnerTests',
  );
}
